ARG BASE_IMAGE="scottyhardy/docker-wine"
ARG TAG="latest"
FROM ${BASE_IMAGE}:${TAG}

RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
        locales \
        tzdata \
        unzip \
        curl \
        ttf-wqy-microhei \
        ttf-wqy-zenhei \
        xfonts-wqy \
        software-properties-common \
        mesa-utils \
        procps \
        pev \
        vim \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -fr /tmp/*

# Setup Wine
RUN winetricks -q msls31 \
    && winetricks -q ole32 \
    && winetricks -q riched20 \
    && winetricks -q riched30 \
    && winetricks -q win7 \
    && rm -fr /usr/share/wine/{gecko,mono} \
    && rm -fr /tmp/* \
    && echo 'Wine Initialized'

ARG root_password
RUN echo "root:${root_password}" | chpasswd \
    && localedef -i zh_CN -c -f UTF-8 zh_CN.UTF-8 \
    && echo "LANG=zh_CN.UTF-8" >> /etc/default/locale \
    && echo "LC_ALL=zh_CN.UTF-8" >> /etc/default/locale

COPY [A-Z]* /root/
COPY VERSION /root/VERSION.docker-wechat
COPY container_root/ /root/bin/
COPY src/winescript /usr/local/bin/
COPY entrypoint.sh /usr/local/bin/
COPY data/wechat_3.6.0.18.tar.gz /root/

# setup wechat
RUN mkdir -p "/root/WeChat Files" "/root/.wine/drive_c/users/user/Application Data" \
    && bash -x /root/bin/setup.sh

COPY data/DaenWxHook.dll /root/.wine/drive_c/Program Files (x86)/Tencent/Wechat/
COPY data/HPSocket4C.dll /root/.wine/drive_c/Program Files (x86)/Tencent/Wechat/[3.6.0.18]/

VOLUME [\
  "/root/WeChat Files", \
  "/root/.wine/drive_c/users/user/Application Data" \
]


